version: "3.8"

services:
  database:
    image: postgres:10.5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "54321:5432"
      
  data-reader-api:
    image: data-reader-api:v1.0.0
    ports:
      - "8085:8080"

volumes:
  database-data: